java-beans
==========

ForRent Java Beans useful across multiple code bases.

== Compiling JAR ==

[source,sh]
----
./gradlew build
----

== Uploading Jar file to mavenrepo.forrent.com ==

You can upload the jar file either from Jenkins or from command line on your local machine.

=== Uploading from Jenkins ===

Create a tag based off of the master branch or any branch.

* If creating a tag based off of master the tag name should follow the semantic versioning convention `\d.\d.\d`. For example 0.0.1.
* If creating a tag based off of other branches the tag name should be as follows `\d.\d.\d-.*`. For example 0.0.1-COR-4345.

Then log into Jenkins and run the "Deploy_Engage121_SDK_to_Maven_Repo" job. The job expects three parameters;

* tag_name: The name of the tag you created.
* maven_repo_username: The mavenrepo.forrent.com username
* maven_repo_password: The mavenrepo.forrent.com password

=== Uploading from local machine ===

Uploading from your local machine is helpful especially when you want to quickly test your changes.

To do this open the gradle.properties file and modify accordingly.

* Set the tag_name to a value like so `\d.\d.\d-.*`. For example 0.0.1-COR-4345.
* Set the maven_repo_username and maven_repo_password

And then run `./gradlew uploadArchives`


