= java-beans =

ForRent Java Beans useful across multiple code bases.

== Compiling JAR ==

[source,sh]
----
./gradlew build
----

== Uploading Jar file to mavenrepo.forrent.com ==

You can upload the jar file either from Jenkins or from command line on your local machine.

=== Uploading from Local Machine ===

1. Increment the tag_name in `/gradle.properties`. Tag should match the pattern  `\d.\d.\d-.*`, for example "0.0.1-COR-4345".
2. Set `maven_repo_username` and `maven_repo_password` in `/gradle.properties`. Request an account if you don't have one.
3. Run `./gradlew uploadArchives`.
4. Hosted versions can be found here: http://dsfrcsatis01.frmsystems.net:8080/index.html#artifact/com.forrent/java-beans

=== Uploading from Jenkins ===

Create a tag based off of the master branch or any branch.

* If creating a tag based off of master the tag name should follow the semantic versioning convention `\d.\d.\d`. For example 0.0.1.
* If creating a tag based off of other branches the tag name should be as follows `\d.\d.\d-.*`. For example 0.0.1-COR-4345.

Then log into Jenkins and run the "Deploy_Java-Beans_To_Maven" job. The job expects three parameters;

* tag_name: The name of the tag you created.
* maven_repo_username: The mavenrepo.forrent.com username
* maven_repo_password: The mavenrepo.forrent.com password

